### PR TITLE
Python and MATLAB examples

### PR DESCRIPTION
**Pull request by ver228**

### CODE REVIEW

**Comment by Ichoran** [comment]
This is great, thanks!  Would you be able to make the following minor modifications?

  (1) Remove the hdf5 and tiff files from version control (so someone downloading this is assured that they are generated afresh by the code they're running)

  (2) Rename ABOUT.MD ABOUT.md in the python directory

  (3) Add which version of Matlab you used in MATLAB/ABOUT.md since older versions of Matlab did _not_ include full HDF5 support.

If you're not familiar with how to update pull requests, let me know.  (It's easy but not completely automatic last I checked, so you have to know what to do.)

(Edit--er, lost track of which username was which person.  I think you probably know what you're doing.  Maybe better than me.)

**Comment by ver228** [comment]
I added the changes you asked. Apparently I just had to update my repository and the pull request got updated.  Cheers.

**Comment by Ichoran** [comment]
Yes, that's how it goes.  Thanks for the changes!

I'm not so sure about adding `.tiff` to .gitignore, though, since the source tiff file is and should remain under version control.  Also, the `hdf5` files are still there and probably shouldn't be (so that if someone downloads it, they're guaranteed that they made the hdf5 file also).  `.hdf5` could definitely be part of version control.

With that, I think we're good to go.  Thanks again!

**Comment by Ichoran** [comment]
By ".hdf5 could be part of version control" I mean ".hdf5 could be in .gitignore".

**Comment by ver228** [comment]
Sorry, I didn't understand before. It is done.

**Pull request merged**
